### ISSUE TITLE
Users can't restart game

### ISSUE THREAD

**Issue by KingofKFCJamal** [nickthegamer5/SteamBattleBot#2]
Everytime I used !setup, it doesn't restart the game.

**Comment by quizque** [comment]
This will be a very easy fix, I'll start working on it as soon as I can. Also thanks for making this issue, would have never thought of it :)

**Comment by KingofKFCJamal** [comment]
No problem

**Comment by quizque** [comment]
!reset command has been added in https://github.com/nickthegamer5/SteamBattleBot/commit/528ec1c52f3f37b05d8d80ccb82ba80f67a5923c
