### ISSUE TITLE
Since update, it kicks me out of Steam Client.

### ISSUE THREAD

**Issue by KingofKFCJamal** [nickthegamer5/SteamBattleBot#4]
Each time I start up the program, it kicks my Steam Client to offline (Yes, I know I am using my main account since there aren't an auto-accept friend requests feature yet :D). And as soon as I restart Steam, it kicks the program offline.

**Comment by quizque** [comment]
They way steam was made it can only have one user on at a time :( so if you use your main account it will be kicked off and if you join back on it will kick the bot off. Nothing I can do sadly but I'll update the README. Just use an alt account instead.

**Comment by quizque** [comment]
Also, their is an auto friend accept but the bot needs to be on when the friend request is made. I'll look into making it do it automatically.

**Comment by KingofKFCJamal** [comment]
I should of guess that with the login, since it does uses Sentry. To the automatic, that would be very helpful.

**Comment by quizque** [comment]
If you wanna just change the account, simply log in with that account, no need to mess around with the sentry file. The auto accept friend requests will be added in next push( If it works! ).

**Comment by quizque** [comment]
Turned out that I already made that a thing! lol, any way you can now friend it > start up the bot > wait 2.5 seconds and it will auto accept.
